win <- trimws(readLines("https://raw.githubusercontent.com/unicode-org/cldr/master/common/supplemental/windowsZones.xml"))

win <- win[grep("<mapZone", win)]

from <- gsub('<mapZone other="([^"]+)" .*', '\\1', win)
to <- gsub('<mapZone other.*territory.*type="([^" ]+?)[" ].*', '\\1', win)

ii <- match(unique(from), from)
.tznames <- data.frame(Windows = from[ii],
                       Olson = to[ii],
                       stringsAsFactors = FALSE)

filename <- "~/Packages/icalutils/R/tznames.R"
cat("## This file is generated by windowZones.R\n\n",
    file = filename, append = FALSE)
dump(".tznames", file = filename, append = TRUE)

library("formatR")
tidy_file("~/Packages/icalutils/R/tznames.R",
          width.cutoff = 20, wrap = TRUE)
