## The data in this file are auto-generated from file 'windowsZones.xml'
## in the Unicode Common Locale Data Repository (http://cldr.unicode.org/).
## See https://www.unicode.org/copyright.html and https://www.unicode.org/license.html.

.tznames <- structure(list(Windows = c("Dateline Standard Time",
    "UTC-11", "Aleutian Standard Time",
    "Hawaiian Standard Time",
    "Marquesas Standard Time",
    "Alaskan Standard Time",
    "UTC-09", "Pacific Standard Time (Mexico)",
    "UTC-08", "Pacific Standard Time",
    "US Mountain Standard Time",
    "Mountain Standard Time (Mexico)",
    "Mountain Standard Time",
    "Yukon Standard Time",
    "Central America Standard Time",
    "Central Standard Time",
    "Easter Island Standard Time",
    "Central Standard Time (Mexico)",
    "Canada Central Standard Time",
    "SA Pacific Standard Time",
    "Eastern Standard Time (Mexico)",
    "Eastern Standard Time",
    "Haiti Standard Time",
    "Cuba Standard Time",
    "US Eastern Standard Time",
    "Turks And Caicos Standard Time",
    "Paraguay Standard Time",
    "Atlantic Standard Time",
    "Venezuela Standard Time",
    "Central Brazilian Standard Time",
    "SA Western Standard Time",
    "Pacific SA Standard Time",
    "Newfoundland Standard Time",
    "Tocantins Standard Time",
    "E. South America Standard Time",
    "SA Eastern Standard Time",
    "Argentina Standard Time",
    "Greenland Standard Time",
    "Montevideo Standard Time",
    "Magallanes Standard Time",
    "Saint Pierre Standard Time",
    "Bahia Standard Time",
    "UTC-02", "Azores Standard Time",
    "Cape Verde Standard Time",
    "UTC", "GMT Standard Time",
    "Greenwich Standard Time",
    "Sao Tome Standard Time",
    "Morocco Standard Time",
    "W. Europe Standard Time",
    "Central Europe Standard Time",
    "Romance Standard Time",
    "Central European Standard Time",
    "W. Central Africa Standard Time",
    "Jordan Standard Time",
    "GTB Standard Time",
    "Middle East Standard Time",
    "Egypt Standard Time",
    "E. Europe Standard Time",
    "Syria Standard Time",
    "West Bank Standard Time",
    "South Africa Standard Time",
    "FLE Standard Time",
    "Israel Standard Time",
    "South Sudan Standard Time",
    "Kaliningrad Standard Time",
    "Sudan Standard Time",
    "Libya Standard Time",
    "Namibia Standard Time",
    "Arabic Standard Time",
    "Turkey Standard Time",
    "Arab Standard Time",
    "Belarus Standard Time",
    "Russian Standard Time",
    "E. Africa Standard Time",
    "Iran Standard Time",
    "Arabian Standard Time",
    "Astrakhan Standard Time",
    "Azerbaijan Standard Time",
    "Russia Time Zone 3",
    "Mauritius Standard Time",
    "Saratov Standard Time",
    "Georgian Standard Time",
    "Volgograd Standard Time",
    "Caucasus Standard Time",
    "Afghanistan Standard Time",
    "West Asia Standard Time",
    "Ekaterinburg Standard Time",
    "Pakistan Standard Time",
    "Qyzylorda Standard Time",
    "India Standard Time",
    "Sri Lanka Standard Time",
    "Nepal Standard Time",
    "Central Asia Standard Time",
    "Bangladesh Standard Time",
    "Omsk Standard Time",
    "Myanmar Standard Time",
    "SE Asia Standard Time",
    "Altai Standard Time",
    "W. Mongolia Standard Time",
    "North Asia Standard Time",
    "N. Central Asia Standard Time",
    "Tomsk Standard Time",
    "China Standard Time",
    "North Asia East Standard Time",
    "Singapore Standard Time",
    "W. Australia Standard Time",
    "Taipei Standard Time",
    "Ulaanbaatar Standard Time",
    "Aus Central W. Standard Time",
    "Transbaikal Standard Time",
    "Tokyo Standard Time",
    "North Korea Standard Time",
    "Korea Standard Time",
    "Yakutsk Standard Time",
    "Cen. Australia Standard Time",
    "AUS Central Standard Time",
    "E. Australia Standard Time",
    "AUS Eastern Standard Time",
    "West Pacific Standard Time",
    "Tasmania Standard Time",
    "Vladivostok Standard Time",
    "Lord Howe Standard Time",
    "Bougainville Standard Time",
    "Russia Time Zone 10",
    "Magadan Standard Time",
    "Norfolk Standard Time",
    "Sakhalin Standard Time",
    "Central Pacific Standard Time",
    "Russia Time Zone 11",
    "New Zealand Standard Time",
    "UTC+12", "Fiji Standard Time",
    "Chatham Islands Standard Time",
    "UTC+13", "Tonga Standard Time",
    "Samoa Standard Time",
    "Line Islands Standard Time"),
    Olson = c("Etc/GMT+12",
        "Etc/GMT+11",
        "America/Adak",
        "Pacific/Honolulu",
        "Pacific/Marquesas",
        "America/Anchorage",
        "Etc/GMT+9",
        "America/Tijuana",
        "Etc/GMT+8",
        "America/Los_Angeles",
        "America/Phoenix",
        "America/Mazatlan",
        "America/Denver",
        "America/Whitehorse",
        "America/Guatemala",
        "America/Chicago",
        "Pacific/Easter",
        "America/Mexico_City",
        "America/Regina",
        "America/Bogota",
        "America/Cancun",
        "America/New_York",
        "America/Port-au-Prince",
        "America/Havana",
        "America/Indianapolis",
        "America/Grand_Turk",
        "America/Asuncion",
        "America/Halifax",
        "America/Caracas",
        "America/Cuiaba",
        "America/La_Paz",
        "America/Santiago",
        "America/St_Johns",
        "America/Araguaina",
        "America/Sao_Paulo",
        "America/Cayenne",
        "America/Buenos_Aires",
        "America/Godthab",
        "America/Montevideo",
        "America/Punta_Arenas",
        "America/Miquelon",
        "America/Bahia",
        "Etc/GMT+2",
        "Atlantic/Azores",
        "Atlantic/Cape_Verde",
        "Etc/UTC", "Europe/London",
        "Atlantic/Reykjavik",
        "Africa/Sao_Tome",
        "Africa/Casablanca",
        "Europe/Berlin",
        "Europe/Budapest",
        "Europe/Paris",
        "Europe/Warsaw",
        "Africa/Lagos",
        "Asia/Amman",
        "Europe/Bucharest",
        "Asia/Beirut",
        "Africa/Cairo",
        "Europe/Chisinau",
        "Asia/Damascus",
        "Asia/Hebron",
        "Africa/Johannesburg",
        "Europe/Kiev",
        "Asia/Jerusalem",
        "Africa/Juba",
        "Europe/Kaliningrad",
        "Africa/Khartoum",
        "Africa/Tripoli",
        "Africa/Windhoek",
        "Asia/Baghdad",
        "Europe/Istanbul",
        "Asia/Riyadh",
        "Europe/Minsk",
        "Europe/Moscow",
        "Africa/Nairobi",
        "Asia/Tehran",
        "Asia/Dubai",
        "Europe/Astrakhan",
        "Asia/Baku",
        "Europe/Samara",
        "Indian/Mauritius",
        "Europe/Saratov",
        "Asia/Tbilisi",
        "Europe/Volgograd",
        "Asia/Yerevan",
        "Asia/Kabul",
        "Asia/Tashkent",
        "Asia/Yekaterinburg",
        "Asia/Karachi",
        "Asia/Qyzylorda",
        "Asia/Calcutta",
        "Asia/Colombo",
        "Asia/Katmandu",
        "Asia/Almaty",
        "Asia/Dhaka",
        "Asia/Omsk",
        "Asia/Rangoon",
        "Asia/Bangkok",
        "Asia/Barnaul",
        "Asia/Hovd",
        "Asia/Krasnoyarsk",
        "Asia/Novosibirsk",
        "Asia/Tomsk",
        "Asia/Shanghai",
        "Asia/Irkutsk",
        "Asia/Singapore",
        "Australia/Perth",
        "Asia/Taipei",
        "Asia/Ulaanbaatar",
        "Australia/Eucla",
        "Asia/Chita",
        "Asia/Tokyo",
        "Asia/Pyongyang",
        "Asia/Seoul",
        "Asia/Yakutsk",
        "Australia/Adelaide",
        "Australia/Darwin",
        "Australia/Brisbane",
        "Australia/Sydney",
        "Pacific/Port_Moresby",
        "Australia/Hobart",
        "Asia/Vladivostok",
        "Australia/Lord_Howe",
        "Pacific/Bougainville",
        "Asia/Srednekolymsk",
        "Asia/Magadan",
        "Pacific/Norfolk",
        "Asia/Sakhalin",
        "Pacific/Guadalcanal",
        "Asia/Kamchatka",
        "Pacific/Auckland",
        "Etc/GMT-12",
        "Pacific/Fiji",
        "Pacific/Chatham",
        "Etc/GMT-13",
        "Pacific/Tongatapu",
        "Pacific/Apia",
        "Pacific/Kiritimati")),
    class = "data.frame",
    row.names = c(NA,
        -139L))
